# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0004_paymentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=45)),
                ('capacity_per_room', models.IntegerField()),
                ('total_capacity', models.IntegerField()),
                ('fee', models.IntegerField()),
            ],
        ),
    ]
