# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0005_accommodationoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accommodationoption',
            old_name='fee',
            new_name='fee_krw',
        ),
        migrations.AddField(
            model_name='accommodationoption',
            name='fee_usd',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
