# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0006_auto_20160801_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'full_view',
                'managed': False,
            },
        ),
    ]
