# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-14 00:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_fullview'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='occupancy',
            field=models.IntegerField(default=0),
        ),
    ]
