# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0008_accommodation_occupancy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='accommodation',
        ),
        migrations.DeleteModel(
            name='Accommodation',
        ),
    ]
