# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0006_auto_20170530_1521'),
        ('registration', '0009_auto_20170530_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='accommodation_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='policy.AccommodationOption'),
            preserve_default=False,
        ),
    ]
