# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0010_participant_accommodation_option'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='accommodation_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participant', to='policy.AccommodationOption'),
        ),
    ]
