# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-04 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0011_auto_20170601_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='recommender_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
